"""Add CheckConstraint so tag names won't be blank

Revision ID: 9c793f24e1e5
Revises: 9de6d0255c2f
Create Date: 2024-01-27 15:02:24.725966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c793f24e1e5'
down_revision = '9de6d0255c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testName', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('testName')

    # ### end Alembic commands ###
